# Generated by Django 5.0 on 2024-01-07 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('start_year', models.IntegerField(verbose_name='Ano de Início')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='Ano de Conclusão')),
                ('present', models.BooleanField(default=False, verbose_name='Atualmente')),
                ('institute', models.CharField(max_length=50, verbose_name='Instituição')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Formação',
                'verbose_name_plural': 'Formações',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('start_year', models.IntegerField(verbose_name='Ano de Início')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='Ano de Conclusão')),
                ('present', models.BooleanField(default=False, verbose_name='Atualmente')),
                ('company', models.CharField(max_length=50, verbose_name='Empresa')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('subject', models.CharField(max_length=50, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='Imagem')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
                ('link', models.CharField(max_length=50, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Portfólio',
                'verbose_name_plural': 'Portfólio',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('birthday', models.DateField(verbose_name='Data de Nascimento')),
                ('website', models.CharField(max_length=50, verbose_name='Website')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('education', models.CharField(max_length=50, verbose_name='Educação')),
                ('freelance', models.BooleanField(verbose_name='Freelance')),
                ('about', models.TextField(verbose_name='Sobre')),
                ('facts', models.TextField(verbose_name='Fatos')),
                ('skills', models.TextField(verbose_name='Habilidades')),
                ('resume', models.TextField(verbose_name='Resumo')),
                ('portfolio', models.TextField(verbose_name='Portfólio')),
                ('services', models.TextField(verbose_name='Serviços')),
                ('testimonials', models.TextField(verbose_name='Testemunhos')),
                ('contact', models.TextField(verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='Plataforma')),
                ('link', models.CharField(max_length=50, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/testimonials', verbose_name='Imagem')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('testimonial', models.TextField(verbose_name='Testemunho')),
            ],
            options={
                'verbose_name': 'Testemunho',
                'verbose_name_plural': 'Testemunhos',
            },
        ),
    ]
