# Generated by Django 5.0.1 on 2024-01-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='facts',
            field=models.TextField(blank=True, null=True, verbose_name='Fatos'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='portfolio',
            field=models.TextField(blank=True, null=True, verbose_name='Portfólio'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='resume',
            field=models.TextField(blank=True, null=True, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='services',
            field=models.TextField(blank=True, null=True, verbose_name='Serviços'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidades'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='testimonials',
            field=models.TextField(blank=True, null=True, verbose_name='Testemunhos'),
        ),
    ]
