# Generated by Django 5.0 on 2024-01-26 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_settings_about_alter_settings_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.CharField(choices=[('about', 'Sobre'), ('facts', 'Fatos'), ('skills', 'Habilidades'), ('resume', 'Resumo'), ('portfolio', 'Portfólio'), ('services', 'Serviços'), ('testimonials', 'Testemunhos'), ('contact', 'Contato')], max_length=30, verbose_name='Local')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subtítulo')),
                ('subtext', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subtexto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/texts', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Texto',
                'verbose_name_plural': 'Textos',
                'ordering': ['spot'],
            },
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_year'], 'verbose_name': 'Formação', 'verbose_name_plural': 'Formações'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_year'], 'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_time'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name'], 'verbose_name': 'Portfólio', 'verbose_name_plural': 'Portfólio'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-percentage'], 'verbose_name': 'Habilidade', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['platform'], 'verbose_name': 'Rede Social', 'verbose_name_plural': 'Redes Sociais'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='about',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='facts',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='services',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='testimonials',
        ),
        migrations.AddField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Horário de Envio'),
            preserve_default=False,
        ),
    ]
