# Generated by Django 5.0 on 2024-01-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_text_delete_testimonial_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='subtext',
            field=models.TextField(blank=True, null=True, verbose_name='Subtexto'),
        ),
    ]
